apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lifehub-ingress
spec:
  rules:
    - host: lifehub.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lifehub-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lifehub-backend-service
                port:
                  number: 80
